version: '3.3'
services:
        bigreplapse:
                container_name: bigreplapse
                restart: unless-stopped
                build:
                        context: ./
                        dockerfile: Dockerfile
                volumes:
                        - "/etc/localtime:/etc/localtime:ro"
                        - "./export:/opt/bigreplapse/export"
                        - "./count.jssh:/opt/bigreplapse/telegram-bot-bash/count.jssh"
                        - "./botconfig.jssh:/opt/bigreplapse/telegram-bot-bash/botconfig.jssh"
                        - "./tmp:/opt/bigreplapse/.tmp"

